# This is a basic workflow to help you get started with Action
name: discord message
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env: 
      MAIN_BRANCH: $GITHUB_REF
    steps:
    - uses: actions/checkout@master
    - name: Running a test command and getting the output
      run: echo '::set-output name=TEST_COMMAND::cat /etc/os-release'
      id: test-command
      if: github.event_name == 'pull_request'
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        args: Secret ${{ secrets.MY_SECRET }} with ${{ steps.test-command.outputs.TEST_COMMAND}}
      if: github.event_name == 'push'
    - name: Test default envs
      run: echo "${{ env.MAIN_BRANCH }}"
      
